spring:
  application:
    name: "Quote API"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

openai:
  api:
    key: ${OPENAI_API_KEY}